GET http://localhost:3000/master/customers/6228aef007bf3d39143ad82
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW5iaWEgU2VuZ2dhZ2F1IiwiZmlyc3RfbmFtZSI6IkFuYmlhIiwibGFzdF9uYW1lIjoiU2VuZ2dhZ2F1IiwiYWRkcmVzcyI6bnVsbCwicGhvbmUiOm51bGwsImVtYWlsIjoibXVoYW1tYWRlc2VuZ2dhZ2F1QGdtYWlsLmNvbSIsInBob25lX2NvbmZpcm1hdGlvbl9jb2RlIjpudWxsLCJwaG9uZV9jb25maXJtZWQiOmZhbHNlLCJlbWFpbF9jb25maXJtYXRpb25fY29kZSI6IjM3ZmY5NmY4LTg4YmEtNDYyNy1hZWIzLTZjNWUxNTYzY2U5MiIsImNyZWF0ZWRfYXQiOiIyMDIyLTAzLTA5VDA3OjQ4OjA0LjcwNFoiLCJ1cGRhdGVkX2F0IjoiMjAyMi0wMy0wOVQwNzo0ODowNC43MDRaIiwidG9rZW5faWQiOiJhMzlhNjE4Zi1kOTkwLTQ2ZTktODhjOS05ZGVkZTRjN2Q1MTAiLCJpZCI6IjYyMjg1YmI0MjA5ZGMwOTEwOTMyYTAzZCIsImlhdCI6MTY0NjgzNTUxNywiZXhwIjoxNjQ2ODM3MzE3fQ.kiXb6bU67wtKi5VfftCeafQAa2xD8IQFxMq6AuCzbA0

###

GET http://localhost:3000/master/customers/download
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW5iaWEgU2VuZ2dhZ2F1IiwiZmlyc3RfbmFtZSI6IkFuYmlhIiwibGFzdF9uYW1lIjoiU2VuZ2dhZ2F1IiwiYWRkcmVzcyI6bnVsbCwicGhvbmUiOm51bGwsImVtYWlsIjoibXVoYW1tYWRlc2VuZ2dhZ2F1QGdtYWlsLmNvbSIsInBob25lX2NvbmZpcm1hdGlvbl9jb2RlIjpudWxsLCJwaG9uZV9jb25maXJtZWQiOmZhbHNlLCJlbWFpbF9jb25maXJtYXRpb25fY29kZSI6IjM3ZmY5NmY4LTg4YmEtNDYyNy1hZWIzLTZjNWUxNTYzY2U5MiIsImNyZWF0ZWRfYXQiOiIyMDIyLTAzLTA5VDA3OjQ4OjA0LjcwNFoiLCJ1cGRhdGVkX2F0IjoiMjAyMi0wMy0wOVQwNzo0ODowNC43MDRaIiwidG9rZW5faWQiOiJhMzlhNjE4Zi1kOTkwLTQ2ZTktODhjOS05ZGVkZTRjN2Q1MTAiLCJpZCI6IjYyMjg1YmI0MjA5ZGMwOTEwOTMyYTAzZCIsImlhdCI6MTY0Njg4ODY4MiwiZXhwIjoxNjQ2ODkwNDgyfQ.y0d9b37VZi301ZmBqXDUmxiGR1xz_q8JNX6QLWT1Ha4

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username" : "anbiasenggagau",
    "password" : "asdasd"
}